### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by LE0616** [benetech/Imageshare-Extensions#10]
This thread is for requesting and submitting external assets for the Imageshare Extension (ex icons, images etc).
Below will be a running draft list of asset needs as they arise. Specifics TBD. 

Icons:
Main Extension Icon
Optional: Submenu Icons

**Comment by LE0616** [comment]
@clapierre I'll post in here as asset needs become more specific.

**Comment by LE0616** [comment]
@clapierre 

For Chrome & Firefox:
1. 128x128 icon - used during installation and by the Chrome Web Store
2. 48x48 icon - used in Chrome extensions management pages and the Add-ons Manager in Firefox
3. Optional 16x16 icon - used as favicon for extension pages

For Safari:
1. 512x512 icon - used as App icon
2. 1024x1024 icon - used as App icon in App Store

**Comment by clapierre** [comment]
@LE0616 So would all these images look the same just in different sizes I assume, and this would be what we want our Imageshare icon to be is the correct?  Also, will there be other Icon's we will need or is this the only one?

**Comment by clapierre** [comment]
Also @sinabahram could we use this Icon on our main Imageshare website as well to help with this branding?  If so would we just use one of those icon images or would we need something like a PNG image or SVG image?

**Comment by sinabahram** [comment]
Yup, we can definitely use the same asset, but you may wish different branding for the extension VS the website. It is up to you.

**Comment by clapierre** [comment]
@LE0616 still blocking on my question above.
IE:
So would all these images look the same just in different sizes I assume, and this would be what we want our Imageshare icon to be is the correct? Also, will there be other Icon's we will need or is this the only one?

**Comment by LE0616** [comment]
@clapierre yes they would look the same, just drawn in the size needed for the context. For now, I'm only seeing the need for the one icon yes. As Sina mentioned it can be your current website icon, or if you wish, you can use a different branding icon to distinguish the site from the extension.

**Comment by clapierre** [comment]
Great, thanks we don't yet have an Imageshare Icon on our website so we will make one that works for both.
Thanks for the clarification, I will now get marketing to help on this.

**Comment by LE0616** [comment]
@clapierre We're also going to need the icons from the "Type" dropdown in Advanced Search. Thanks :D

**Comment by clapierre** [comment]
@LE0616 Where would you like me to upload them to as we already have them in the main Imageshare Repo I believe.

**Comment by LE0616** [comment]
@clapierre  Oh of course, great! I'll grab them from the repo.

**Comment by clapierre** [comment]
Here is the idea we are thinking for the Logo.
There are a few options here one of which I think will replace the Website ImageShare Logo  in the top left corner of all pages (its a rectangular Logo.  But there are a couple square shaped logos for the extension one that is only an image of an outline of a mountain with an arrow up representing the sharing option, the other two options is the same image with the text either in all Uppercase or our traditional "Imageshare" text below that.  I am leaning towards the Mixed case option since that is the current branding but wanted to get your opinion if having the text in that icon would be a problem or not?

So my preference for 
Large Scale Logo would be 2 for the website (alt text: "Logo: Imageshare, A Benetech Initiative")
Small Scale Logo either 1 or 3 for the extension (alt text: "Logo Imageshare")

Love to hear your opinions. 

![Imageshare Logo Mock Up 2](https://user-images.githubusercontent.com/7736749/108903210-e4130b00-75d1-11eb-811d-980f52077b98.png)

**Comment by sinabahram** [comment]
Please never use all-caps for anything, full stop.

Other than that, no observations on my end.

**Comment by clapierre** [comment]
@LE0616 So what works best in my question above concerning the thumbnail logo for the extension?

**Comment by LE0616** [comment]
@clapierre #1 of Small Scale Logo is my preference for the extension thumbnail. The use cases for extensions are rarely large enough for readability of text. @sinabahram do you concur?

**Comment by clapierre** [comment]
I was thinking the same thing @LE0616 so #1 of the Small Scale Logo's would be best for the extension.

I will get my marketing department to then make this Logo What format should it be?  JPEG, PNG, SVG?

for these following sizes:
For Chrome & Firefox:

128x128 icon - used during installation and by the Chrome Web Store
48x48 icon - used in Chrome extensions management pages and the Add-ons Manager in Firefox
Optional 16x16 icon - used as favicon for extension pages
For Safari:

512x512 icon - used as App icon
1024x1024 icon - used as App icon in App Store

**Comment by sinabahram** [comment]
test it at 400% zoom, if good, then I agree.

**Comment by LE0616** [comment]
@clapierre If you could shoot me jpg and svg that would be great.

**Comment by clapierre** [comment]
@LE0616 I have pushed the new imageshare logos to use to the repo under a new folder "icons" feel free to move them to where you would like.

**Comment by LE0616** [comment]
@clapierre wonderful. thank you so much.

**Comment by LE0616** [comment]
@clapierre Would it be possible to get "Imageshare-logo-no-text.png" in a 1.5:1 ratio size?

**Comment by clapierre** [comment]
@LE0616 Here you go, its large but easy to scale it to the size you need.
[Imageshare-logo-no-text-3000x2000.png](https://benetech.box.com/s/cs25k43b77yaay718tcxfq0wdw5wyn5l)

**Comment by jkva** [comment]
Closing as no longer a relevant issue - the assets are currently part of the various build targets.
