### ISSUE TITLE
API Usage Instructions

### ISSUE THREAD

**Issue by LE0616** [benetech/Imageshare-Extensions#12]
Incorporating Imageshare API, replacing direct URL search.

**Comment by LE0616** [comment]
@jkva Let's chat API use instructions here.

**Comment by LE0616** [comment]
From @jkva for reference:
A plain listing of resources can be loaded via: https://imgsdev.wpengine.com/json-api/resources/
That's on the dev instance
You can use search via this syntax: https://imgsdev.wpengine.com/json-api/resources/filter/?query=fish

**Comment by jkva** [comment]
Other endpoints available at this moment: 

https://imgsdev.wpengine.com/json-api/types/
https://imgsdev.wpengine.com/json-api/accommodations/
https://imgsdev.wpengine.com/json-api/subjects/
https://imgsdev.wpengine.com/json-api/sources/

**Comment by LE0616** [comment]
@jkva  Let me know when ${IMGS_API_URL}filter/?query=${selection}&subject=${userSubject}&type=${userType}&acc=${userAcc}&src=${userSrc} API call, as discussed in Slack, is up and running. This is not blocking.

**Comment by jkva** [comment]
Closing as since addressed and currently functional.
