### ISSUE TITLE
Search and Custom Search should invoke dialog when no selection detected

### ISSUE THREAD

**Issue by sinabahram** [benetech/Imageshare-Extensions#16]
This is mainly to address the issue that will unfortunatley happen on Windows where a screen reader user has highlighted text, but the extension will not know about this. This is because of the virtual buffers that said screen readers use.

Therefore, let's not disable or inactive Search or Custom Search when there's no selection. Instead let's pop up a JS alert that simply has a message (exact language TBD from @clapierre  and myself), with an input field, and ok/cancel, which simply offers the opportunity for the person to type in the words they wnat to search ImageShare for.

@LE0616  happy to discuss further on our Wednesday call.

**Comment by LE0616** [comment]
Got it. I already have some code mocked up for a search from input ready to go so this can happen relatively quickly. I'll add it to my todos.
