### ISSUE TITLE
Git Workflow

### ISSUE THREAD

**Issue by LE0616** [benetech/Imageshare-Extensions#2]
Do you have a preferred workflow for dealing with version control in Git (rules around how to use and name branches, when to commit and commit message structure, rules around merging, etc)?

**Comment by sinabahram** [comment]
Let's do feature branches, make sure that when you merge them back into dev, you comment on the issue being closed with a brief explanation and a reference to the resolution (GitHub should link that directly if you simply reference the commit or PR). I think feature branches should be pushed frequently and often, but never ever assumed to be stable. If you're working on a feature branch, this lets you commit/push often to it so as to mitigate anything being only on your machine but alleviates any pressure to do 100 commits, which you should feel free to do. Rebasing/squashing can happen later of course.

@jkva  please fill in with anything I haven't covered.
