### ISSUE TITLE
Internal Documentation for Loading Extensions

### ISSUE THREAD

**Issue by sinabahram** [benetech/Imageshare-Extensions#24]
We need in a readme or separate markdown file some simple instructions for how to install each of the extensions from the repository. This is only for folks like @clapierre, not for the general public.

**Comment by LE0616** [comment]
Heading and list markup added to readme in oddsnends branch. Branch to be merged end of day today 4/22.

**Comment by LE0616** [comment]
Branch is merged. Please let me know if there are any other changes you'd like for ReadMe.

**Comment by sinabahram** [comment]
Closing for now, but @clapierre  please reopen of course if additional readme changes are needed.
