### ISSUE TITLE
Details for search feature in extension

### ISSUE THREAD

**Issue by sinabahram** [benetech/Imageshare-Extensions#26]
@jkva  here are some takeaways from @clapierre  and my conversation about this feature.

Note, I casually refer to /search-terms as an endpoint (call this whatever you want, but it's simply a made up endpoint because it is the union of two other fields (tags and resource titles) in the system with some filtering).

1. /search-terms returns the union of all tags and all words in all titles of resources that are greater than 3 characters long. This means all tags are included independent of length, and all words from titles that are 4 letters or longer as well. This is the list of items that will be used to search the text of hte page.
2. Each entry in this list will map to a location on Imageshare. That way, the resulting dialog that comes up in the browser knows where to send people when they hit enter, click OK, etc.

Note, I'm not sure if /tags is an existing API endpoint, but if it isn't, it should be, because tags are a known entity in Imageshare.

Note, we use the word "keywords" on the UI for tags, which I will go make another issue in the Imageshare repository (not this one) to go fix this simple thing to bring everything into alignment. See below for link.

**Comment by sinabahram** [comment]
I will also go reference this issue from the Imageshare repository to make the pure API isue request. In the mean-time, here is a related issue on the UI side of things in Imageshare.

https://github.com/benetech/Imageshare/issues/270

**Comment by jkva** [comment]
@clapierre @sinabahram 

I've done initial work on this feature. It's fairly expensive - meaning there's a search through a DOM tree, intersecting with a list of 3K+ keywords, while also filtering for nodes that don't contain interactive elements such as `button` or `anchor` in their parent tree such that I don't generate nested interactive elements.

I'm working on adding some more accessibility work such as notifying the user that imageshare is "searching..." and adding a sr-only text to the generated links.

Effectively each found term is wrapped by a custom styled link which shows the imageshare logo. These links direct to a search results page for the keyword.

Note: this is not yet in the builds, I'll continue work on it tomorrow.

![Screenshot of the Scientific American website, showing some words wrapped in custom Imageshare anchors, such as "News", "Natural" and "Robin"](https://user-images.githubusercontent.com/217264/120706473-6fe1e080-c4b9-11eb-999d-bb5f1a4d5b7e.png)

**Comment by jkva** [comment]
@clapierre the current `chrome-mv2` and `chrome-mv3` builds support an early version of this feature; can you play around with it?

I've not yet tested this in safari, and it works in firefox but is quite a bit slower than the chrome versions, but I'd rather wait with debugging that once we've agreed on the general functionality.

Other than that the CSS needs some hardening so that existing CSS on a host page will not conflict with the extension's CSS.

**Comment by clapierre** [comment]
@jkva @sinabahram 
Well this definitely works, but I am thinking we should really just restrict this to Keywords only and not try to add any more say words from the Title of each resource etc. as this is really finding a LOT of highlighted words which I wasn't expecting to be honest.

Just going to the http://diagramcenter.org/
there are over 50 links here.  Have we already restricted just to the Keywords?  Just wondering if this will be overload if its not bringing up just the most relevant image share resources.

What do you think?

**Comment by jkva** [comment]
@clapierre by keywords you mean WordPress post tags?

We can either reduce by post tags, or run the list of terms through a stop words list. Something like https://gist.github.com/sebleier/554280.

**Comment by clapierre** [comment]
Sorry yes Wordpress Tags.  Lets see how that works, but maybe that other idea of yours could work as well.  Might be easier just to try just the tags to see how that improves the results. 
Maybe its fine just seemed to me that we had a lot of hits in which case its not really that useful right?

**Comment by jkva** [comment]
I'll work on that stopword list later this week. Just pushed a commit that adds a large speed increase, for chrome as well for firefox 👍

**Comment by clapierre** [comment]
Perfect, and btw Amazing on the speed improvement, WOW that is now super quick!  Well done.

**Comment by jkva** [comment]
Glad to hear it :) the list of keywords is now filtered through a list of common English stopwords.

**Comment by clapierre** [comment]
@jkva I don't see any new code for this new filtered common english stopwords.

**Comment by jkva** [comment]
Happens server-side.

**Comment by jkva** [comment]
@clapierre can this feature be considered complete?

**Comment by clapierre** [comment]
I think this still needs some work.

I thought we were also going to have an option so a Screen reader user could get a list of words on this page that would be highlighted which they could pick from instead of pressing the button to highlight the words on the page then going link by link to see which words were highlighted.

Also I don't think that modification you did on the server worked, or maybe it did but I can't see it working because we are hitting the main Server not the Dev Server?

Here is a screen shot from Wikipedia showing the highlighted words: "with", "that", "have", etc.)

![Screen Shot Chrome Canary with 80% or more of the words highlighted including non keywords](https://user-images.githubusercontent.com/7736749/121531561-607bff00-c9b3-11eb-8e21-8b2f1cf95b74.png)

**Comment by jkva** [comment]
@clapierre The list of terms coming from the server gets cached for a day (extension-side) and currently gets loaded from the dev instance.

That said - I've modified the code to render keyword search results, render them in a dropdown and allow the user to press a button to view the results.

![A screen capture of the extension popup showing "56 keywords found in page" with a dropdown listing the keywords. To the right of the dropdown there is a button labeled "View results"](https://user-images.githubusercontent.com/217264/121576805-146ba180-ca29-11eb-8684-22cbd7792553.png)

This seems more practical than rendering an entire dialog with all the semantics that it entails. Can you let me know what you think?

**Comment by clapierre** [comment]
I think we can keep the link version (ideally that would be a setting to include it or not on the page?)
But I do like how you have added that new dropdown list.  Some folks may want to see where in the document these words appeared so I think there is still value for having that but if it's not too much extra to have that be an option I think that would be the perfect solution.  Default with having it turned on.

Options under the Have the focus on the new Tab would be:
[Checkbox] Include Links to Keywords on webpage. 

If thats too much extra then lets just include it always for now but keep the new addition on how many words were found and the option to view the list of words like you just added is perfect.

**Comment by jkva** [comment]
An issue I've found with the link version is that it can break layouts since a page's CSS is tightly coupled to DOM structure and the insertion of anchor elements breaks the existing layout. On that node the current solution is overall better.

If you still prefer to have the option to also show the links, let me know :)

**Comment by clapierre** [comment]
I think having the option would be nice, maybe have it off by default then. if thats acceptable.

**Comment by jkva** [comment]
Will do 👍

**Comment by clapierre** [comment]
In any event I think we are very close!  Thanks Job, this is excellent work!

**Comment by jkva** [comment]
I've added the links as a toggle option. Give it a whirl 👍

**Comment by clapierre** [comment]
Works great @jkva.
The only small issue I see is that when I go to one of the results found from either clicking on the new link in the document or clicking on the "View Results" button in the Imageshare popup is that it brings you to Imageshare inside this same tab.  To be consistent we should bring up the results in a new tab.

**Comment by jkva** [comment]
Agreed 👍 will do.

**Comment by jkva** [comment]
The "View selected term" button now opens in a new tab and makes that tab active depending on the "Active tab" setting.
All highlighted keywords (if that setting is used) are now buttons which behave similarly.

**Comment by sinabahram** [comment]
Question on pedantic semantics: these should be links not buttons, correct? Links go places. Buttons do things.

**Comment by jkva** [comment]
@sinabahram agreed - initially they were. However if they are supposed to create a new tab which is potentially set as the active tab, this can only be achieved by a button. Alternatively they remain anchors with a potential `target` attribute, as they were before. Personally I'm no fan of either, and would prefer that highlighted keywords are regular links, leaving the remaining choice of how to use these to the user.

**Comment by sinabahram** [comment]
I should have caught this earlier, so I apologize. Best practice is to never open new tabs without the user explicitly indicating this choice. The user can always choose to open something in a new tab, but they cannot choose to not open something in a new tab. @clapierre  I'd like to back out this change as it isn't the accessible way of doing things. One can always command+click for this functionality if they are links per @jkva's suggestion.

**Comment by jkva** [comment]
Agreed. And changing this is fairly minimal in either case.

**Comment by clapierre** [comment]
This is fine, just seems odd if the user chose to have imageshare results in a new tab with focus this is the only features which the user then also has to do an extra Shift click when the activate the link on page. but a right click / search imageshare brings up the same word in a new focused tab which is an option in settings.

**Comment by jkva** [comment]
This should now be implemented as expected (the highlighted keywords reverted to anchors). @clapierre please close this issue if you agree with its current implementation.

**Comment by clapierre** [comment]
Saw this implemented. Thanks.
