### ISSUE TITLE
No search field initially when clicking on Imageshare plugin icon

### ISSUE THREAD

**Issue by clapierre** [benetech/Imageshare-Extensions#27]
Canary:Chrome mv3 (Mac)
When nothing on the page is selected and you click on the Imageshare Icon, the user is forced to first pick either Standard or Advance search first before it recognizes nothing was selected then provides the option with the search field.

![Screenshot of Imageshare plugin menu: Initially no search field present on click.  Showing only Standard Search button and Advance Search button](https://user-images.githubusercontent.com/7736749/115593240-1f0b8500-a289-11eb-9459-6876a4c03906.png)

![Screenshot of Imageshare plugin menu: Once selecting either button then the search field is present followed by the same two Standard Search and Advance Search buttons.](https://user-images.githubusercontent.com/7736749/115593264-27fc5680-a289-11eb-9246-78ca74263187.png)

Maybe we can always bring up the Search field and populate it with what the user has selected otherwise it would be blank?

**Comment by LE0616** [comment]
@sinabahram @jkva This is a change I can make. Is it alright to go ahead?

**Comment by sinabahram** [comment]
Yes, please

**Comment by LE0616** [comment]
Enhancement is available for testing in main.

**Comment by clapierre** [comment]
Confirmed!  This now works. :)
