### ISSUE TITLE
When  performing a search no feedback given

### ISSUE THREAD

**Issue by clapierre** [benetech/Imageshare-Extensions#28]
Chrome: Canary mv3 (Mac)

When either I select text and do a right click search (standard or advance), or clicking on the button Standard / Advance search from the icon plugin (top right corner of the screen)

There is no indication that anything is happening while the search is being performed.

Can/should we pop up some "Search in progress..." change to a working cursor or something?  @sinabahram suggestions?  Right now if it takes a while it doesn't look like anything is happening.

**Comment by LE0616** [comment]
@clapierre @sinabahram Since this is generally a very short period of time, I really like the idea of a working cursor with maybe a corresponding screen reader announcement.

**Comment by clapierre** [comment]
That works for me.

**Comment by sinabahram** [comment]
Working cursor works for now. @LE0616  can you please close this issue once that's pushed?

**Comment by LE0616** [comment]
On it. Will do @sinabahram .

**Comment by jkva** [comment]
This has been part of the extension for a while now -- in addition a hidden screen reader announcement is read out when the search starts.
