### ISSUE TITLE
Scaffolding

### ISSUE THREAD

**Issue by LE0616** [benetech/Imageshare-Extensions#3]
Begin file layout via branch "scaffolding".

**Comment by LE0616** [comment]
Scaffolding is in place, hot reload bundler, and autoprefixer in place and working.  The following warning was thrown by parcel, but does not block primary function. Consider the suggested change for future iteration. 

- @parcel/transformer-postcss: WARNING: Using a JavaScript PostCSS config file means losing out on caching features of Parcel. Use a .postcssrc(.json) file whenever possible.

**Comment by sinabahram** [comment]
Given that we're in a super-early stage, is it possible to address this warning?

**Comment by LE0616** [comment]
Absolutely! :D

**Comment by LE0616** [comment]
change complete, and working as expected, no warnings.
