### ISSUE TITLE
Icon missing initially when right click menu appears

### ISSUE THREAD

**Issue by clapierre** [benetech/Imageshare-Extensions#31]
Chrome:canary mv3 (Mac)

Initially when you select some text and do a right click the Imageshare icon is missing as shown here:

![screenshot of Imageshare right click menu initially showing an empty space where the Imageshare Icon should be followed by text "Search Imageshare"](https://user-images.githubusercontent.com/7736749/115599630-ae686680-a290-11eb-835b-446c806a55d5.png)

when you select that item revealing its two children of Standard/Advance search the icon is now visible as shown here.

![screenshot of Imageshare right click menu after you reveal the Imageshare submenu by selecting that menu item, shows the blue background of both the Imageshare Icon in white and the text Imageshare also in white with the blue background of the selected menu item.](https://user-images.githubusercontent.com/7736749/115599768-d1931600-a290-11eb-9d86-4172b5fa36aa.png)

Looks like a white image on a white background issue perhaps?

**Comment by clapierre** [comment]
Furthermore, with FireFox I don't see this problem the Imageshare Icon is in Black in both initially and when selected to bring up the submenu of imageshare.

![screenshot in Firefox of right click menu showing correctly the black imageshare Icon.](https://user-images.githubusercontent.com/7736749/115766478-e2a95900-a35c-11eb-94a7-31bf222d4f62.png)

![screenshot in Firefox of right click menu sowing correctly the highlighted black imageshare icon revealing the children menu.](https://user-images.githubusercontent.com/7736749/115766498-e806a380-a35c-11eb-930d-a893bff4e683.png)

**Comment by LE0616** [comment]
All icons defaulting to black across browsers. Closing this issue and creating a new one for dark mode accommodations.
