### ISSUE TITLE
Options are not remembered and no confirmation save was complete

### ISSUE THREAD

**Issue by clapierre** [benetech/Imageshare-Extensions#32]
Chrome:Canary (Mac)

When I go into the Options and change anything say subject:Engineering when I click on save nothing happens.
I exit the tab. Go back into Imageshare Options and nothing is still selected.  Not sure where the issue is here.

**Comment by LE0616** [comment]
@clapierre When you click on save then, you aren't getting the "your search criteria has been saved" notification?

**Comment by LE0616** [comment]
@jkva The options not showing on reload is that same issue you and I were working on the other day. All the appropriate attribute changes are made but that initiating render is using the title div view instead of anything in the list. Any ideas how to tweak that?

**Comment by clapierre** [comment]
correct, nothing happens the button presses and I see no change what so ever.  Even with Voice Over turned on there is no announcement or confirmation that I pressed the button or settings were saved.

**Comment by jkva** [comment]
Should now be addressed in all build targets as of 41f183d15b9d583f79caac0f358d6659bd402f2c and further.

**Comment by clapierre** [comment]
I now see the confirmation that my settings were saved and they are also remembered which is great!
