### ISSUE TITLE
Advance Search doesn't do anything

### ISSUE THREAD

**Issue by clapierre** [benetech/Imageshare-Extensions#33]
Chrome:canary mv3 (Mac)

When I either right click and perform an Advance Search or from the Icon in the top right corner of the browser doing an Advance search gives no feedback and nothing happens.

**Comment by clapierre** [comment]
looking at the inspector I got the following message

Service-worker has loaded via background.js.
background.js:186 Selection Object: "machines"
background.js:160 You have not yet set criteria for advanced searching. Please go to options to enable Advanced Search
background.js:169 response null


So this explains why it fails but still no popup notice shown.

**Comment by LE0616** [comment]
@jkva @sinabahram This is another one that works fine on my end. Are either of you able to duplicate? Is it possible some of this is an incompatibility of Chrome with a Mac?

**Comment by jkva** [comment]
I'm unable to replicate this. OSX 10.15.6 Catalina, Chrome Canary 92.0.4499.0.

I searched for a term using the right-click context menu and I get a notification both on advanced and standard search.

@clapierre is this problem still occurring for you?

**Comment by jkva** [comment]
This seems related to the way notifications are handled; the extension makes it seem as if they're coming from the website itself, and not from the extension. Hence if notifications are disabled for the website where the extension is being used, no notifications will show. I'll see if this can be handled some other way.

**Comment by sinabahram** [comment]
Just commenting to keep in mind the relationship to #30, with the solution hopefully fixing both.

**Comment by jkva** [comment]
Yep, already left a similar comment on that ticket regarding this relationship.

**Comment by clapierre** [comment]
I know this isn't complete, just giving an update.
Definitely making progress here with the latest build.  

Now wen no Advance options are chosen it brings up the options pane and I can choose something.  no confirmation yet but at least it saves it now.  

Then when I perform either from the plugin menu or right click menu and do an advance search it now brings me to the Imageshare page with no results found which is odd because when I just click on the regular "Search Library" button on our website with the given filters it finds the 3  resources it should. So not sure what it initially searched for but at least the parameters are working. 
ie.
I had "2.5D tactile graphic" as my Type, and searched for "cell". This should find 3 with that filter, or 185 without the 2.5D type only "cell" doing a regular Search.

This was with Canary.
Canary: https://imageshare.benetech.org/?page=search&q=cell&subject=0&type=226&acc=0&src=0

**Comment by clapierre** [comment]
With FireFox Dev.
Just about the same behavior as above except when I land on the results from the advance search I have a new filter showing up which is very odd


    Type: "2.5D Tactile Graphic" Source: "search-source-" 

What is "seach-source-"?

Here is the URL produced
FireFox: https://imageshare.benetech.org/?page=search&q=Cell&subject=0&type=226&acc=0&src=search-source-

**Comment by jkva** [comment]
Related to #49 - sorted via b976671dacddc8fcaad5c62945245a24862eb66b
