### ISSUE TITLE
Chrome:developer mv2 issues / errors

### ISSUE THREAD

**Issue by clapierre** [benetech/Imageshare-Extensions#34]
Attempting to just load the plugin by going to 

chrome://extentions
and unpacking src-chrome-firefox as was instructed in the ReadMe.md file (btw this is on my Mac.)

I got the following warnings / errors 

## Warning: Unrecognized manifest key 'browser_specific_settings'.

 "browser_specific_settings": {
    "gecko": {
      "id": "lauren@larundatech.com",
      "strict_min_version": "42.0"
    }
  },
(where this entire section is highlighted in yellow)

## Permission 'menus' is unknown or URL pattern is malformed.
"permissions": [
    "contextMenus",
    "notifications",
    "storage",
    "nativeMessaging",
    "activeTab",
    "bookmarks",
    "menus",
    "*://*/*"
  ],

(Where "menus", is highlighted in yellow)

## Error in event handler: ReferenceError: browser is not defined

       // create listener for this item that launches Options page onClick
        browser.menus.onClicked.addListener(() => {
          if (browser.runtime.openOptionsPage) {
            browser.runtime.openOptionsPage();
          } else {
            window.open(browser.runtime.getURL('options.html'));
          }
        })
      }
    }

    if (browser === undefined) {
      return
    }

(Where:     if (browser === undefined) {
      return 
is highlighted in yellow)

Didn't proceed any further testing since it looked like there may be some issues here which needs to be addressed first.

**Comment by sinabahram** [comment]
You are making sure to run this in Chrome dev like we discussed and using mv3, right?

**Comment by clapierre** [comment]
I was using chrome dev but loaded src-chrome-firefox since I was trying to test the mv2 like the read me suggested. before switching to testing on Firefox.

**Comment by LE0616** [comment]
@clapierre These are all normal for now, pre build-targets. That first bit of code is for Firefox and is only needed during development. It will be removed altogether for production. Chrome doesn't know what it's for but just ignores it. The second one, the "menu" permission, similarly is specific to Firefox and is ignored by Chrome. The third is a check for the browser object. In Chrome it is undefined like you see in the warning and nothing happens. In firefox, browser is defined which triggers some Firefox specific code that allows you to right click the bookmark icon and see the "Options" menu item, like you do in Chrome by default. None of this should be interfering in any way to extension processes in Chrome.

**Comment by clapierre** [comment]
Ok, will test that tomorrow then, but maybe we should add this info to the readme to ignore these warnings/errors.
Thanks
