### ISSUE TITLE
Firefox Warning when installing plugin

### ISSUE THREAD

**Issue by clapierre** [benetech/Imageshare-Extensions#35]
Not sure if this is expected just wanted to flag what I saw when I installed the manifest.json file from the src-chrome-firefox folder.

Warning details

Reading manifest: Warning processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.

feel free to close if expected.  Maybe we should put a note in the readme if this is expected.

**Comment by LE0616** [comment]
@clapierre This is another one of those chrome v firefox things but on the other side. Chrome no longer allows persistent background scripts so persistent = false is mandated. I'll add this and the other ones like it to the readme.
