### ISSUE TITLE
Options not available from toolbar?

### ISSUE THREAD

**Issue by clapierre** [benetech/Imageshare-Extensions#37]
Firefox: 

The readme says: " In Options, accessed via right licking the Imageshare icon and selecting Options, ..."

I don't see this.  All I see is TItle "Imageshare Search" with 2 buttons "Run Standard Search" and "Run Advance Search". Where is options?

![screenshot of Firefox Imageshare toolbar plugin when clicked on showing only the two search buttons with no options link/button etc.](https://user-images.githubusercontent.com/7736749/115768772-97dd1080-a35f-11eb-93eb-6366d7e0168e.png)

**Comment by LE0616** [comment]
@clapierre It should show the popup on left click and the menu items including Options on right click.  On a Mac this may be CTRL + click. See this apple support article for more:
[https://support.apple.com/guide/mac-help/right-click-mh35853/mac](url)

**Comment by sinabahram** [comment]
@LE0616  can you therefore please fix the readme language to reflect proper mouse behaviors on Mac?

@clapierre  if the above makes sense, please close this issue but open another if the proper mouse behavior does not result in what you expect.

**Comment by clapierre** [comment]
Yes that makes sense and works, so I can get into options with a right click on the mac.  adding to the readme is a good idea.
I thought I tried that guess I missed the button since it was white on white ;)
