### ISSUE TITLE
Unable to select Advance Search options

### ISSUE THREAD

**Issue by clapierre** [benetech/Imageshare-Extensions#38]
Firefox: Developer Edition
When I get to the Imageshare options by going to the page about:addons
I see the Imageshare advance search options, however I am unable to select any option.
I see all the available options, and even see for type the ICON in addition to the text description as expected.
However I am unable to select any of the options either via keyboard or mouse.

When I try to click on an option the dropdown list goes away but my choice isn't selected it remains as: -- choose a subject -- or -- choose a type --

If I try with a keyboard hitting down arrow opens the dropdown list of choices showing me the list of options but pressing down arrow again does nothing, I see no highlighted selection of the list item I expected to see highlighted as I attempt to move down my list of choices.

**Comment by jkva** [comment]
Addressed via PR #41.

**Comment by clapierre** [comment]
Confirmed this is fixed now.
