### ISSUE TITLE
Dark Mode Accomodation

### ISSUE THREAD

**Issue by LE0616** [benetech/Imageshare-Extensions#42]
Dark mode code has been added, but may not yet be supported across browsers. Should be working in Safari at least. Leaving open for testing and to troubleshoot possible options for unsupported browsers.

**Comment by LE0616** [comment]
Icons change for dark mode in Firefox
Icon change not working in Chrome
Some icons change in Safari, but not all

Job will be experimenting to work out the bugs here where possible.

**Comment by jkva** [comment]
There do seem to be some iffy browser differences on this functionality. [This stackoverflow page](https://stackoverflow.com/questions/58880234/toggle-chrome-extension-icon-based-on-light-or-dark-mode-browser) seems useful and thorough, yet the suggested implementation does not seem to be solid cross-browser. Leaving open for now.

**Comment by jkva** [comment]
@clapierre A few things here:

1) in chrome, the main badge icon responds to a dark theme (the icon is changed to white)
2) there appears to be no setting to change the icon for the context menu at runtime.

I'll see what else can be done - perhaps a configuration setting to explicitly switch.

**Comment by sinabahram** [comment]
We've spent a ton of time on this already, and we're fighting against Chrome. If Google wishes to make their browser more accessible, we can revisit; otherwise, I'm closing this out for now as it is out of our control.

**Comment by clapierre** [comment]
understood.
