### ISSUE TITLE
Advance Search returns 0 items found

### ISSUE THREAD

**Issue by clapierre** [benetech/Imageshare-Extensions#49]
Chrome: Canary & dev
With "Images" selected as type
and the text "cell" selected as the search terms

I get to the Imageshare Search results pPage but it says nothing was found
Here is the URL:
https://imageshare.benetech.org/?page=search&q=cell&subject=0&type=229&acc=0&src=0

And if I do nothing but press "Search" again it finds the 7 resources it should.

The reason I figured out is that the "0" for the filters not selected is the problem.  this query should look like
https://imageshare.benetech.org/?page=search&q=cell&subject=&type=229&acc=&src=
Not what we are currently doing which add's those 0's
ie: https://imageshare.benetech.org/?page=search&q=cell&subject=0&type=229&acc=0&src=0

**Comment by jkva** [comment]
Fixed via b976671dacddc8fcaad5c62945245a24862eb66b

**Comment by clapierre** [comment]
Confirmed working now!
