### ISSUE TITLE
Content Menu (CM) Incorporation

### ISSUE THREAD

**Issue by LE0616** [benetech/Imageshare-Extensions#5]
See branch "content-menu"
Goals:
- In MV3 context, create test CM entrees including an option for parent and child entries submenus. (completed)
- Prettify: Remove test strings. Add Imageshare specific titles, icons, contexts, etc.
- Optional: Expand onClick to make our site to site request

Questions:
- Do you have web-ready icons for Imageshare that you would like used as extension icons? If so where can those be accessed?
- I'd like to merge at CM completion with simple onClick, then create a new branch for our primary onClick function since that function is the heart of what we're trying to do as a whole. Does that sound good to you?

**Comment by sinabahram** [comment]
@clapierre  can get you icons, but he'll need to know exactly what icons you need. If you can put a list here or make a separate issue for this topic, Charles can get you those assets.

**Comment by clapierre** [comment]
Yes let me know what you are thinking of and in addition to the list of icons will be used to identify also the technical requirements (PNG, SVG, size, shape etc.)

**Comment by LE0616** [comment]
I'll create a new issue for this one and we can go from there.
