### ISSUE TITLE
Imageshare new tab is not in focus

### ISSUE THREAD

**Issue by clapierre** [benetech/Imageshare-Extensions#50]
Chrome canary & Dev
Even with this checked in options:  Imageshare as Active Tab
I stay on the current page even though a new Imageshare tab is brought up with my search result

**Comment by clapierre** [comment]
Not sure if its related or not but when checking on the extension I did see the following error
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
Context
popup.html
Stack Trace
popup.html:0 (anonymous function)

**Comment by jkva** [comment]
Fixed via 9e0781f2046e80def8c0f125fb2f192837b7871d

**Comment by clapierre** [comment]
Confirmed working now.
