### ISSUE TITLE
When I first perform an Advance Search I am no longer taken to Options

### ISSUE THREAD

**Issue by clapierre** [benetech/Imageshare-Extensions#51]
If I haven't set up my advance options I am no longer taken to the Advance options pane.
Instead a new Search tab in Imageshare appears with the text I am searching for with all the advance options as 0 and the result is nothing is found
IE:
https://imageshare.benetech.org/?page=search&q=Cell&subject=0&type=0&acc=0&src=0
Nothing is found because of the 0's for subject, type, acc and src
Normally when we don't have those selected it would instead be
https://imageshare.benetech.org/?page=search&q=Cell&subject=&type=&acc=&src=

If I haven't picked anything in the advance options I would expect to be taken to the advance Options pane where I can choose some filter.

This now happens in Chrome and Firefox.

Previously it worked correctly where it brought up the options tab for this extension but this no longer behaves this way.

**Comment by jkva** [comment]
Fixed via 9e0781f2046e80def8c0f125fb2f192837b7871d

**Comment by clapierre** [comment]
Confirmed fixed!
