### ISSUE TITLE
Options: Type using mouse to select the option clicking on icon

### ISSUE THREAD

**Issue by clapierre** [benetech/Imageshare-Extensions#52]
When I brought up the options and tried to select the type, I used the mouse to show the dropdown list which shows the list of available types, but if I click on the Icon instead of the text beside the icon, the dropdown goes away but that item is not chosen.

IE: if your mouse is hovering overtop of the "Image" Icon and you click the image the type doesn't get selected but the dropdown collapses as if it registered your choice.

**Comment by jkva** [comment]
Fixed via 79a8a92a323c892287d7d5ccbf257fe74c365169

**Comment by clapierre** [comment]
confirmed working
