### ISSUE TITLE
Options for Types lists everything

### ISSUE THREAD

**Issue by clapierre** [benetech/Imageshare-Extensions#53]
On the Imageshare website when I go to advance Options "Type" I get a list of 7 choices each with its associated Icon.

However in the Extension's Options I am seeing the entire list of 11 choices 4 of which doesn't exist in Imageshare yet.

**Comment by jkva** [comment]
The API wasn't filtering out types which weren't containing resource files - this should now be sorted.
![A screenshot portion of the extension options showing an expanded "type" dropdown showing 7 available types.](https://user-images.githubusercontent.com/217264/120852692-d4b13f80-c57a-11eb-85a3-03b1eebd6d3b.png)

**Comment by clapierre** [comment]
Confirmed working
