### ISSUE TITLE
Default option to switch focus to new Imageshare results tab

### ISSUE THREAD

**Issue by clapierre** [benetech/Imageshare-Extensions#54]
I thought the default was to move the focus over.

@sinabahram Is there a reason why this changed?
Now users must go into options to select this as their default.  I would expect it to switch to the new tab by default.

**Comment by clapierre** [comment]
BTW Both FF and Chrome Canary had this same issue.

**Comment by jkva** [comment]
Could be regression from the build target conversion. I'll change it to be on by default.

**Comment by jkva** [comment]
Fixed in 381510fe57d64888ed93a043a4f30bfbadeb3fb7.

**Comment by clapierre** [comment]
Confirmed working now.
