### ISSUE TITLE
Advance Search 

### ISSUE THREAD

**Issue by clapierre** [benetech/Imageshare-Extensions#55]
When you haven't selected any advance search parameters but only change the default focus to Imageshare doing a advance search does not bring up the Options tab.

Steps to Reproduce.

1. Uninstall / reinstall the extension.
2. Go to the Imageshare Extension options and select the " Imageshare as Active Tab" checkbox & Save the settings
3. Do an advance Search for anything.
4. Result is a normal search with no advance filters selected

Should have brought up the Options Pane (since none of the Advance filters were selected.)

**Comment by jkva** [comment]
Addressed in 381510fe57d64888ed93a043a4f30bfbadeb3fb7.

**Comment by clapierre** [comment]
Confirmed focus now the default.
