### ISSUE TITLE
When searching for an item that isn't in Imageshare the notification is cut off with ...

### ISSUE THREAD

**Issue by clapierre** [benetech/Imageshare-Extensions#56]
Here is a screen shot showing the notification cut off.  Maybe just shorten the text?

![Screenshot of the notification being cut off with ... in its place](https://user-images.githubusercontent.com/7736749/122075552-06ae7700-cdaf-11eb-888f-f85775792df4.png)

**Comment by jkva** [comment]
I've considered that. Something like 'No results for "Wikipedia"` and cut off the search term at a particular maximum as well.

**Comment by jkva** [comment]
What I've done for now is maxed out the search term length and cut it off with an ellipsis above 10 characters. I've also tweaked the notification messages. 

This is in the latest build, via 96671f2395e2e33d38ab3644669fa7a56c9f9c5d. Let me know what you think.

![A screenshot of a browser notification reading '20 matches for "communica…"'](https://user-images.githubusercontent.com/217264/122104824-5f662a00-ce18-11eb-9ec1-606afd5f962d.png)

**Comment by clapierre** [comment]
Yes this works.  Thanks
