### ISSUE TITLE
When using the dropdown Imageshare search focus not on input field

### ISSUE THREAD

**Issue by clapierre** [benetech/Imageshare-Extensions#57]
Shouldn't we have the focus on the edit field when entering here or when the they press the search button when nothing is defined?

![Screen Shot: Edit field box not in focus after error](https://user-images.githubusercontent.com/7736749/122076196-863c4600-cdaf-11eb-9327-ebad5828e06b.png)

Steps.
1. click on the Imageshare Icon in the toolbar.
2. (Focus not brought to the edit field (I would think that would be default behavior)

or
1. Clear the Edit field (leave it blank)
2. Press Standard or Advance Search button.
3. Error message appears but focus is not brought back to the edit field to type something in.

**Comment by jkva** [comment]
@clapierre agreed. Focus should go to the input field and the field is described by the error (I think that's already the case) - will fix.

**Comment by jkva** [comment]
Sorted via 7cd0272b262f07191c3b91b63209f130738b483c.

**Comment by clapierre** [comment]
@jkva Not sure if it was this change or the other one, but I just got a crash when I tried with Chrome Canary with the latest build, when doing a simple imageshare search.

Worked fine with FF Dev.

**Comment by jkva** [comment]
I've had crashes in Chrome canary as well. But given it's Canary, I'm not holding my breath. As long as it works in Chrome stable, I'm happy.

**Comment by clapierre** [comment]
This is the first time I have every seen a crash and can't get it to work at all even if I uninstall and reinstall the extension.  seems odd this just started happening and I can't get it to work again.
Is there some debug logs I can check?

**Comment by jkva** [comment]
I've been trying to debug this since it started happening a few days ago. I'm tempted to say it's a change in Canary, but I've not seen any useful debugging information in any of the involved scripts.

**Comment by sinabahram** [comment]
Folks, I'm closing this. Canary has issues like this all the time, and until we can replicate in production, it's difficult to do anything about this. We can reopen if it pops up in a prod release of Chrome.
