### ISSUE TITLE
Browser Specific Specialization Strategy

### ISSUE THREAD

**Issue by LE0616** [benetech/Imageshare-Extensions#6]
Now that we have some working user experience, we'll be looking at duplicating that functionality across browsers. Some of this is done for use by our dependencies but a process for testing and edits will be needed.

Goal:
- working branch can be easily converted for Chrome, Safari and Firefox.

Questions:
- What would we like the process, or strategy, to be for doing this?

**Comment by sinabahram** [comment]
Safari next after Chrome, then Firefox is the priority list. No other browsers are in scope.

**Comment by LE0616** [comment]
How is version control typically handled for this? Do we create new branches for each Browser?

**Comment by sinabahram** [comment]
I recommend using build targets. Branches, in my opinion, should always be eventually merged or mergeable back in.

@jkva  you got opinions?

**Comment by LE0616** [comment]
Ok so I've got the context menu working Safari. Unfortunately just running conversion on the files wasn't enough. As we talked about an MV2 version of our code has to be used making for 2 Manifest.json files, the Safari specific .plist file had to be edited post-conversion, and our code had to be tweaked in background.js. So far while a lot of our code is shared, not many whole files are. @jkva Given these details how would you organize the files moving forward? And how might a build target handle the post-conversion changes?

**Comment by LE0616** [comment]
Firefox on the other hand, though it also only accepts MV2, requires only very minor changes to the MV2 code.

**Comment by jkva** [comment]
Regarding build targets I would use parceljs' `targets` support, where targets use different entry files. Then the target configuration can be used to output to a separate build dir in the dist directory. https://github.com/parcel-bundler/parcel#targets

Depending on the need for conversion between targets you might want to do some dynamic code generating using templating. `parcel` has `pug` templating support built-in, if I recall.

Which targets are we looking at?

* Chrome-MV2
* Chrome-MV3
* Safari (MV2?)
* Firefox (MV2)

What are the particular differences between builds we're aware of? Might be good to document in this issue 👍

**Comment by LE0616** [comment]
@jkva This looks perfect, thanks. 
 
Current targets are:
- Chrome (MV3)
- Safari (MV2)
- Firefox (MV2)

Though it does seem worth while giving Chrome MV2 it's own target.

Firefox is easy, just a switch from chrome. to browser. calls and the use of MV2.
Safari requires our files, in MV2, be run through their converter, then .plist file created by the conversion edited for use of the context menu, then the background file edited slightly. Would it be helpful to create comments showing the code itself before and after?

**Comment by jkva** [comment]
Implemented as part of ticket #21.
