### ISSUE TITLE
MVP: Primary onClick Function

### ISSUE THREAD

**Issue by LE0616** [benetech/Imageshare-Extensions#7]
Goals:
- onClick, in either our context menu or main-menu drop down, we trigger an ImageShare search of selection or input that works, successfully sending a query to ImageShare in a way that is understood by the site and outputs a result.
- Positive result yields opening of Imageshare to search results
- Negative result yields notification

Questions: TBD

**Comment by sinabahram** [comment]
@jscholes  I'm interested how this will work with a screen reader like NVDA or Jaws and virtual cursor highlighting. One would assume it doesn't because of it being a virtual buffer, but I know for a fact my context menu respects certain selections made with a screen reader, so there's more to it than just that.

**Comment by jscholes** [comment]
@LE0616 how is the element of interest passed to the context menu handler?  Do you have to obtain it yourself based on focus, X/Y coordinates of the menu popup or something like that?  Or does Chrome take care of it?

**Comment by LE0616** [comment]
@jscholes Chrome is handling it mainly. Our primary context is via "selection", so the user would need to highlight the terms or phrases they'd like to search. We gain access to the onClick data via 2 objects, "info" and "tab". Unfortunately, the default info gathered isn't enough for contexts Link, Image, Video or Audio. Those contexts only offer the associated URL rather than items like alt text, caption, title or anything usable for a search fuzy or otherwise, so pulling from those would likely require something more custom.

**Comment by jscholes** [comment]
> Chrome is handling it mainly. Our primary context is via "selection", so the user would need to highlight the terms or phrases they'd like to search.

@sinabahram I suppose the question here is, does selecting text with JAWS and NVDA active actually pass that selection through to the browser?  My initial feeling would probably be yes for NVDA, and a potential no for JAWS.  But there may not be a problem.

**Comment by sinabahram** [comment]
Yes, @jscholes  that's exactly my question.

**Comment by LE0616** [comment]
Closing since the resolution to above block has it's own issue.
